# Generated by Django 2.2.6 on 2020-11-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201119_2338'),
        ('posts', '0005_auto_20201120_1407'),
    ]

    operations = [
    ]
